### PR TITLE
Attempts to repair more of the closing tags.

### LINKED ISSUE #20: Make end tag cleaning more robust.
In #19 we made a first pass at cleaning up a truncated XML-RPC response. Let's improve the approach to handle cases where more than just the end tag is broken.

### PR DESCRIPTION
**Pull request by aerych**
Closes #20 
Attempts to repair more than just a truncated closing tag.

### CODE REVIEW

**Comment by aerych** [comment]
cc @astralbodies Would you be up for a very vicious review of this change?

**Comment by aerych** [comment]
I just realized @astralbodies is going to be out of pocket for a bit.  @sendhil or @diegoreymendez would either of you mind taking a look?

**Comment by diegoreymendez** [comment]
@aerych - Will do!

File: WPXMLRPC/WPXMLRPCDataCleaner.m [hunk 1]
```diff
@@ -82,18 +84,18 @@ @implementation WPXMLRPCDataCleaner (CleaningSteps)
...
+
+    size_t inbytesleft, outbytesleft;
+    inbytesleft = outbytesleft = data.length;
+
+    char *inbuf  = (char *)data.bytes;
+    char *outbuf = malloc(sizeof(char) * data.length);
+    char *outptr = outbuf;
+
+    if (iconv(cd, &inbuf, &inbytesleft, &outptr, &outbytesleft) == (size_t)-1) {
+        // Failed iconv, possible errors to encounter in `errno`:
```
Comment (diegoreymendez) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: Just double checking since I don't see any obvious difference here... you just changed the indentation, correct?

File: WPXMLRPC/WPXMLRPCDataCleaner.m [hunk 2]
```diff
@@ -191,30 +193,54 @@ - (NSString *)cleanWithTidyIfPresent:(NSString *)str {
...
-        range = [str rangeOfString:@"</fault>" options:NSBackwardsSearch];
+        closingTags = @"</value></fault></methodResponse>";
     } else {
-        range = [str rangeOfString:@"</params>" options:NSBackwardsSearch];
+        closingTags = @"</param></params></methodResponse>";
+    }
+
+    // If the length of the content cleaned from before the preamble is greater
+    // than the length of the closing tags, then the xml is too damaged to repair.
+    if (length > closingTags) {
```
Comment (diegoreymendez) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: Should probably be:

`if (length > [closingTags length]) {`

File: WPXMLRPC/WPXMLRPCDataCleaner.m [hunk 3]
```diff
@@ -191,30 +193,54 @@ - (NSString *)cleanWithTidyIfPresent:(NSString *)str {
...
+    // Find the start of the last end tag
+    range = [str rangeOfString:@"<" options:NSBackwardsSearch];
+    if (range.location == NSNotFound) {
+        // This should never happen, but handle the one in a million case.
+        return str;
     }
 
+    // Find the ending stub
+    NSString *stub = [str substringFromIndex:range.location];
+    range = [closingTags rangeOfString:stub];
```
Comment (diegoreymendez) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: Not sure if this is possible, so please bear with me..

Is it possible str could end in `</param><`?  If so, then the ending stub would be `<`, and the code would duplicate the last `</param>` tag ending the variable str with `</param></param></params></methodResponse>`.

If this was possible, then it could be a better idea to look at the end of `str` for any partial match of `closingTags` directly.

**Comment by diegoreymendez** [comment]
@aerych - First run is finished... anything you need let me know!

File: WPXMLRPC/WPXMLRPCDataCleaner.m (hunk 1 above)
Comment (aerych) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: An unintentional change.  I think Xcode took care of the formatting due to some copy/pasting.  Since its switching tabs to spaces its actually more inline with our coding standards.  Call it a happy accident. :)

File: WPXMLRPC/WPXMLRPCDataCleaner.m (hunk 2 above)
Comment (aerych) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: DoH! Yes. Yes it should.

File: WPXMLRPC/WPXMLRPCDataCleaner.m (hunk 3 above)
Comment (aerych) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: Oh good catch! Yes, it does indeed look like that is possible. Will fix.

**Comment by aerych** [comment]
Thanks @diegoreymendez.  I've updated with changes, and added some unit tests.  Ready for a second look if you're available.  Otherwise pinging @sendhil :)

File: WPXMLRPC/WPXMLRPCDataCleaner.m (hunk 1 above)
Comment (diegoreymendez) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: All good... was a bit worried I may be missing something else.

File: WPXMLRPCTest/Tests/WPXMLRPCDataCleanerTest.m [hunk 4]
```diff
@@ -11,20 +11,61 @@ - (void)testClosingTagRepaired
...
+    // Test a whole response
     NSString *completeResponse = @"<methodResponse><params><param><value><string>Hello!</string></value></param></params></methodResponse>";
-    NSString *truncatedResponse = [completeResponse substringWithRange:NSMakeRange(0, [completeResponse length] - 20)];
-    NSString *cleanedString = [cleaner cleanClosingTagIfNeeded:truncatedResponse];
-    STAssertEqualObjects(truncatedResponse, cleanedString, @"Should not try to fix a response that is too damaged.");
+    NSString *cleanedString = [cleaner cleanClosingTagIfNeeded:completeResponse lengthOfCharactersPrecedingPreamble:0];
+    STAssertEqualObjects(completeResponse, cleanedString, @"A good reponse should just be returned intact.");
 
-    completeResponse = @"<methodResponse><params><param><value><string>Hello!</string></value></param></params></methodResponse>";
+    // Test a whole response but some info was cleaned from before the preamble
```
Comment (diegoreymendez) [inline WPXMLRPCTest/Tests/WPXMLRPCDataCleanerTest.m]: First off, very nice work with the amount of unit tests provided.

However, it seems to me like it could be a good idea to break these up into different tests.  It would make the code slightly more readable and the tests easier to maintain.

File: WPXMLRPC/WPXMLRPCDataCleaner.m [hunk 5]
```diff
@@ -191,30 +193,77 @@ - (NSString *)cleanWithTidyIfPresent:(NSString *)str {
  the length of these extra leading characters.
  Check for a good closing tag, and try to repair a broken closing tag.
  */
-- (NSString *)cleanClosingTagIfNeeded:(NSString *)str
+- (NSString *)cleanClosingTagIfNeeded:(NSString *)str lengthOfCharactersPrecedingPreamble:(NSInteger)length
 {
+    // Clean responses, but not requests (for now).
+    if ([str rangeOfString:@"methodResponse"].location == NSNotFound) {
```
Comment (diegoreymendez) [inline WPXMLRPC/WPXMLRPCDataCleaner.m]: This is a purely style comment.  I'm being a bit nitpicky, so feel free to disagree.

I couldn't find any obvious logic mistakes in this code.  However one thing that I did notice when reading this method is that following the logic is a bit difficult.  I feel this is backed up a bit by the amount of comments in the code.

There are two suggestions I can make, to make this method slightly easier to follow:

1. Add some extra `BOOL`s to make the conditions being checked more obvious to the reader.  For example instead of:

```objective-c
if ([str rangeOfString:@"methodResponse"].location == NSNotFound) {
```

Use:

```objective-c
BOOL strContainsAResponse = ([str rangeOfString:@"methodResponse"].location != NSNotFound);

if (!strContainsAResponse) {
```

2. Break this method up into sub methods so that instead of having these lines inline...

```objective-c
NSString *closingTags;
if ([str rangeOfString:@"<params>"].location == NSNotFound) {
    closingTags = @"</value></fault></methodResponse>";
} else {
    closingTags = @"</param></params></methodResponse>";
}
```

...we have...

```objective-c
NSString *closingTags = [self closingTagsForRequest:str];
```

**Comment by diegoreymendez** [comment]
Eric - Second review is complete.  If you happen to agree on my comments, but prefer to leave that for later, feel free to open a different issue and ping me back so I approve this PR.

Also if you disagree just ping me back and I'll approve your PR since I didn't find any problems with it.

File: WPXMLRPCTest/Tests/WPXMLRPCDataCleanerTest.m (hunk 4 above)
Comment (aerych) [inline WPXMLRPCTest/Tests/WPXMLRPCDataCleanerTest.m]: Fair point. I considered it but it felt like more boiler plate just to test the different test cases for a single method. Simple to add more methods if it feels easier to maintain.

**Comment by aerych** [comment]
@diegoreymendez Updated for readability.  Round three? :)

**Comment by diegoreymendez** [comment]
Aight, thanks @aerych let's :shipit: !
